[package]
name = "mandel-wasm"
version = "0.1.0"
authors = ["Adam Wolff <awolff@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
num-complex = "0.3.0"
image = "0.23.11"
num-traits = "0.2.14"
